In [37]:
import numpy as np
import pandas as pd

## Practice Questions for numpy
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [25]:
A = np.linspace(0,6,3)
print(A)
B = np.zeros(3)
print(B)
V = np.vstack((A,B))
print(V)
H = np.hstack((A,B))
print(H)

[0. 3. 6.]
[0. 0. 0.]
[[0. 3. 6.]
 [0. 0. 0.]]
[0. 3. 6. 0. 0. 0.]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [26]:
print(np.intersect1d(A, B))

[0.]


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [27]:
def withinRange(arr, low, high):
    return(A[(A>=low)&(A<=high)])

print(withinRange(A,0,4))

[0. 3.]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#print(iris_2d.shape)
def filter(arr):
    return(arr[(arr[:,2] > 1.5) & (arr[:,0] < 5.0)])

print(filter(iris_2d))


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [30]:
df[['Manufacturer', 'Model', 'Type']][::20]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [31]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean().round(2))
#df['Min.Price'].mean().round(2) = 7.12
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean().round(2))
#df['Max.Price'].mean().round(2) = 21.46
df.head()

#can use lambda?

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small      12.90   15.9      18.80      25.0   
1          NaN   Legend  Midsize      29.20   33.9      38.70      18.0   
2         Audi       90  Compact      25.90   29.1      32.30      20.0   
3         Audi      100  Midsize      17.12   37.7      44.60      19.0   
4          BMW     535i  Midsize      17.12   30.0      21.46      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

3. How to get the rows of a dataframe with row sum > 100?

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df[df.sum(axis=1) > 100]

0   1   2   3
1   17  32  35  30
2   34  28  20  20
4   35  23  21  33
5   12  35  34  28
6   10  29  35  29
10  31  38  11  36
11  39  24  26  32
12  31  26  35  12
13  28  37  11  29